[pytest]
testpaths = .
python_files = test_*.py
markers =
    post_test: mark a test as post_test
    get_test: mark a test as get_test
    positivity: mark a test as positivity
    negativ:emark a test as negativ
    cors_test:emark a test as cors_test

